### ISSUE TITLE
Filtre orders

### ISSUE THREAD

**Issue by cigogma** [celdotro/marketplace#2]
Salut, incerc sa filtrez comenzile prin api dar nu reusesc sa imi dau seama de ce nu merge niciun input.
comenzile vin dar nu sunt filtrate dupa data sau start si limit nu functioneaza.
![image](https://user-images.githubusercontent.com/19759658/83422078-aa8de480-a431-11ea-9c23-36ed79936b57.png)

**Comment by xiopt** [comment]
Salut. Asigura-te ca trimiți datele cu headerul Content-type: form-data si nu JSON.
